"""Damping-factor comparison for SM S4.7 (Table S31 and the numbers in its text).

CIF is computed at the main-text damping d = 0.85 and again at d = 0.95 on the
same graph and seed set. This script reports

  1. agreement between the two runs over every journal and conference:
     Pearson r and Spearman rho of aggregate and of normalized CIF, the
     Spearman rho within the publication-volume pool (>= 1,000 works, indexing
     services excluded), and the overlap of the two top-20 lists;
  2. Table S31: Pearson r and Spearman rho of aggregate and normalized CIF
     against JIF and SJR at both damping values, over every journal and
     conference carrying the metric (the samples of Table 1A). A venue a run
     does not score counts as zero, so the d = 0.85 columns equal the CIF rows
     of Table 1A;
  3. the overlap between each CIF top 20 and the top 20 by JIF or SJR.

Normalized CIF is recomputed as summed CIF / works at full precision.
Writes figs/discount_corr.tex (Table S31) and prints the text numbers.
"""
import csv
import os
import sys

import numpy as np
from scipy.stats import pearsonr, spearmanr

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from venue_data import DATA_PATH, COL_CIF_AGG, COL_JIF, COL_SJR, COL_NWORKS, load_data_s1
from emit_cn_tables import EXCLUDE, tex_num

_HERE = os.path.dirname(os.path.abspath(__file__))
OUT_TEX = os.path.join(_HERE, "figs", "discount_corr.tex")
VENUE_TYPES = ("j", "c")
MIN_WORKS = 1000
TOP = 20


def fnum(v):
    try:
        return float(v) if v not in (None, "", "NA") else None
    except ValueError:
        return None


def load():
    d95 = {r["source_id"]: float(r.get("total_score") or 0.0)
           for r in load_data_s1("cif_damping_095")}
    rows = []
    with open(DATA_PATH) as f:
        for r in csv.DictReader(f):
            if r.get("source_type") not in VENUE_TYPES:
                continue
            n = fnum(r.get(COL_NWORKS)) or 0.0
            a85 = fnum(r.get(COL_CIF_AGG)) or 0.0
            a95 = d95.get(r["source_id"], 0.0)
            rows.append({
                "name": (r.get("source_name") or "").strip(), "n": n,
                "agg85": a85, "agg95": a95,
                "norm85": a85 / n if n else 0.0, "norm95": a95 / n if n else 0.0,
                "JIF": fnum(r.get(COL_JIF)), "SJR": fnum(r.get(COL_SJR)),
            })
    return rows


def top(rows, key, k=TOP):
    return set(sorted(range(len(rows)), key=lambda i: -rows[i][key])[:k])


def main():
    rows = load()
    print(f"journals and conferences: {len(rows):,}")

    # 1. agreement between the two damping values
    pool = [r for r in rows if r["n"] >= MIN_WORKS and r["name"] not in EXCLUDE]
    for lvl in ("agg", "norm"):
        x = [r[lvl + "85"] for r in rows]; y = [r[lvl + "95"] for r in rows]
        xp = [r[lvl + "85"] for r in pool]; yp = [r[lvl + "95"] for r in pool]
        ov = len(top(rows, lvl + "85") & top(rows, lvl + "95"))
        print(f"{lvl:4s} d=0.85 vs 0.95, all venues: r = {pearsonr(x, y)[0]:.4f}, "
              f"rho = {spearmanr(x, y).correlation:.3f}; volume pool "
              f"(n = {len(pool):,}): rho = {spearmanr(xp, yp).correlation:.3f}; "
              f"top-{TOP} shared: {ov}/{TOP}")

    # 2. Table S31 and 3. top-20 overlap with the prestige metric
    cells = {}
    for lvl in ("agg", "norm"):
        for m in ("JIF", "SJR"):
            sub = [r for r in rows if r[m] is not None]
            mv = [r[m] for r in sub]
            out = [len(sub)]
            for d in ("95", "85"):
                v = [r[lvl + d] for r in sub]
                out += [pearsonr(v, mv)[0], spearmanr(v, mv).correlation]
            tm = top(sub, m)
            ov = [len(tm & top(sub, lvl + d)) for d in ("95", "85")]
            cells[(lvl, m)] = out
            print(f"{lvl:4s} vs {m}: n = {out[0]:,}  d=0.95 r {out[1]:.3f} rho {out[2]:.3f}"
                  f"  d=0.85 r {out[3]:.3f} rho {out[4]:.3f}  top-{TOP} overlap "
                  f"with {m}: d=0.95 {ov[0]}, d=0.85 {ov[1]}")

    def row(lvl, m):
        n, r95, s95, r85, s85 = cells[(lvl, m)]
        return (f"{m} & {tex_num(n)} & {r95:.3f} & {s95:.3f} & {r85:.3f} & "
                f"{s85:.3f} \\\\")

    tex = [
        r"% Autogenerated by damping_095_analysis.py",
        r"\begin{table}[h!]", r"\centering",
        r"\caption[CIF against prestige metrics at $d = 0.85$ and $d = 0.95$]"
        r"{\textbf{CIF against prestige metrics at $d = 0.85$ and $d = 0.95$.} "
        r"Pearson $r$ and Spearman $\rho$ of aggregate and normalized CIF against "
        r"JIF and SJR at both damping values. The comparison runs over every journal "
        r"and conference carrying the metric, the samples of Table~1A.}",
        r"\label{tab:discount-corr}", r"\footnotesize",
        r"\begin{tabular}{@{}lrrrrr@{}}", r"\toprule",
        r" & & \multicolumn{2}{c}{$d = 0.95$} & \multicolumn{2}{c}{$d = 0.85$ (main)} \\",
        r"\cmidrule(lr){3-4}\cmidrule(l){5-6}",
        r"Metric & $n$ & $r$ & $\rho$ & $r$ & $\rho$ \\", r"\midrule",
        r"\multicolumn{6}{@{}l}{\textit{Aggregate CIF}}\\",
        row("agg", "JIF"), row("agg", "SJR"), r"\midrule",
        r"\multicolumn{6}{@{}l}{\textit{Normalized CIF}}\\",
        row("norm", "JIF"), row("norm", "SJR"),
        r"\bottomrule", r"\end{tabular}", r"\end{table}",
    ]
    os.makedirs(os.path.dirname(OUT_TEX), exist_ok=True)
    with open(OUT_TEX, "w") as f:
        f.write("\n".join(tex) + "\n")
    print(f"wrote {os.path.relpath(OUT_TEX, _HERE)}")


if __name__ == "__main__":
    main()
