"""
Emit LaTeX longtables for S3.4 (Commercialization overperformers,
extended). Two lenses on the same pool:
  * MAGNITUDE  : residual from linear fit CIF_intensity ~ JIF, with the
                 actual/predicted multiplier reported alongside.
  * RANK-GAP   : percentile(CIF_intensity) minus percentile(JIF).

Pool: venues with JIF present, CIF-intensity > 0, and >= MIN_WORKS
works. Same pool as the main-paper scatter (Panel D) and rankings.py.

Display names are lightly normalized: OpenAlex title casing is preserved
except for a small set of known lower-cased entries (e.g. "Chemical
engineering progress" -> "Chemical Engineering Progress").

Outputs:
    figs/top_overperformers_magnitude.tex   longtable body
    figs/top_overperformers_rankgap.tex     longtable body
"""
import os
import numpy as np
from scipy.stats import rankdata

from venue_data import (load_rows, num, venues_only,
                    COL_CIF_NORM, COL_JIF, COL_NAME, COL_NWORKS)

FIGS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "figs")
os.makedirs(FIGS, exist_ok=True)
MIN_WORKS = 1000   # venue size floor, counted over all document types
TOP_N = 30

# Small display-name overrides (OpenAlex casing quirks).
DISPLAY_OVERRIDES = {
    'PLANT PHYSIOLOGY': 'Plant Physiology',
    "Chemical engineering progress": "Chemical Engineering Progress",
    'Proceedings of SPIE, the International Society for Optical Engineering/Proceedings of SPIE': 'Proceedings of SPIE',
    'Methods in enzymology on CD-ROM/Methods in enzymology': 'Methods in Enzymology',
    '2009 IEEE Conference on Computer Vision and Pattern Recognition': 'IEEE Computer Vision and Pattern Recognition',
    'Proceedings - International Conference on Image Processing': 'International Conference on Image Processing',
}


def latex_escape(s):
    if s is None:
        return ""
    s = s.replace("&", r"\&")
    s = s.replace("_", r"\_")
    s = s.replace("%", r"\%")
    s = s.replace("#", r"\#")
    s = s.replace("$", r"\$")
    return s


UNICODE_FIX = {
    '′': "$'$",
    '’': "'",
    '″': "$''$",
    '‘': '`',
    '“': '``',
    '”': "''",
    '–': '--',
    '—': '---',
    '\xa0': ' ',
    '−': '$-$',
}


def _fix_unicode(s):
    for _k, _v in UNICODE_FIX.items():
        s = s.replace(_k, _v)
    return s


def display_name(name):
    return _fix_unicode(DISPLAY_OVERRIDES.get(name, name))


def truncate(s, n):
    return s if len(s) <= n else s[:n - 1] + "\\ldots{}"


def build_pool():
    rows = load_rows()
    venues = venues_only(rows)
    pool = []
    for r in venues:
        jif = num(r, COL_JIF)
        cif = num(r, COL_CIF_NORM)
        na = num(r, COL_NWORKS) or 0
        if jif is None or cif is None or na < MIN_WORKS or cif <= 0:
            continue
        pool.append({"name": r[COL_NAME], "jif": jif, "cif": cif * 1e4})
    n = len(pool)
    jif = np.array([d["jif"] for d in pool])
    cif = np.array([d["cif"] for d in pool])
    coef = np.polyfit(jif, cif, 1)
    jif_pct = rankdata(jif) / n * 100
    cif_pct = rankdata(cif) / n * 100
    for i, d in enumerate(pool):
        pred = np.polyval(coef, jif[i])
        d["pred"] = pred
        d["resid"] = cif[i] - pred
        # actual / predicted; guard against nonpositive predictions from
        # the linear fit at very small JIFs (intercept can be slightly < 0
        # in principle, though it isn't in this fit).
        d["mult"] = cif[i] / pred if pred > 0 else float("inf")
        d["jif_pct"] = jif_pct[i]
        d["cif_pct"] = cif_pct[i]
        d["gap"] = cif_pct[i] - jif_pct[i]
    return pool, n, coef


def emit_magnitude(pool, n_pool):
    rows = sorted(pool, key=lambda x: x["resid"], reverse=True)[:TOP_N]
    out = []
    out.append(r"% Autogenerated by emit_overperformers.py")
    out.append(r"\begin{longtable}{r p{0.28\textwidth} r r r r r r}")
    out.append(
        r"\caption[Top " + str(TOP_N) + r" commercialization overperformers by magnitude]{\textbf{Top " + str(TOP_N)
        + r" commercialization overperformers by \textit{magnitude}.} Defined as the residual "
        r"of normalized CIF from a linear fit against JIF over the pool of "
        + f"{n_pool:,}"
        + r" venues with JIF, normalized CIF $> 0$, and at least "
        + f"{MIN_WORKS:,}"
        + r" works. Normalized CIF is reported in units of $10^{-4}$. "
        r"``$\times$ vs.\ pred.'' is the multiplier of actual over linear-fit prediction. "
        r"JIF and CIF percentiles are within the pool.}"
        r"\label{tab:overperformers-magnitude}\\"
    )
    out.append(r"\toprule")
    out.append(r"Rank & Venue & JIF & \shortstack[r]{Norm.\ CIF\\($10^{-4}$)} & Resid.\ & $\times$ vs.\ pred.\ & JIF \% & CIF \% \\")
    out.append(r"\midrule\endfirsthead")
    out.append(r"\multicolumn{8}{l}{\emph{Table~\ref{tab:overperformers-magnitude} (continued)}}\\")
    out.append(r"\toprule Rank & Venue & JIF & \shortstack[r]{Norm.\ CIF\\($10^{-4}$)} & Resid.\ & $\times$ vs.\ pred.\ & JIF \% & CIF \% \\ \midrule\endhead")
    out.append(r"\bottomrule\endfoot")

    for i, d in enumerate(rows, 1):
        venue = latex_escape(display_name(d["name"]))
        jif = f"{d['jif']:.1f}"
        cif = f"{d['cif']:.1f}"
        resid = f"{d['resid']:.1f}"
        mult = f"{d['mult']:.1f}" if np.isfinite(d["mult"]) else "--"
        jp = f"{d['jif_pct']:.0f}"
        cp = f"{d['cif_pct']:.0f}"
        out.append(
            f"{i} & {venue} & {jif} & {cif} & {resid} & {mult} & {jp} & {cp} \\\\"
        )

    out.append(r"\end{longtable}")
    with open(os.path.join(FIGS, "top_overperformers_magnitude.tex"), "w") as f:
        f.write("\n".join(out) + "\n")
    print(f"wrote figs/top_overperformers_magnitude.tex  ({TOP_N} rows)")


def emit_rankgap(pool, n_pool):
    rows = sorted(pool, key=lambda x: x["gap"], reverse=True)[:TOP_N]
    out = []
    out.append(r"% Autogenerated by emit_overperformers.py")
    out.append(r"\begin{longtable}{r p{0.37\textwidth} r r r r r}")
    out.append(
        r"\caption[Top " + str(TOP_N) + r" commercialization overperformers by rank gap]{\textbf{Top " + str(TOP_N)
        + r" commercialization overperformers by \textit{rank gap}.} Defined as normalized-CIF "
        r"percentile minus JIF percentile within the same pool of "
        + f"{n_pool:,}"
        + r" venues (JIF present, normalized CIF $> 0$, at least "
        + f"{MIN_WORKS:,}"
        + r" works). Normalized CIF is reported in units of $10^{-4}$. "
        r"This lens surfaces venues whose commercialization ranking is far above their JIF ranking.}"
        r"\label{tab:overperformers-rankgap}\\"
    )
    out.append(r"\toprule")
    out.append(r"Rank & Venue & JIF & \shortstack[r]{Norm.\ CIF\\($10^{-4}$)} & JIF \% & CIF \% & Gap \\")
    out.append(r"\midrule\endfirsthead")
    out.append(r"\multicolumn{7}{l}{\emph{Table~\ref{tab:overperformers-rankgap} (continued)}}\\")
    out.append(r"\toprule Rank & Venue & JIF & \shortstack[r]{Norm.\ CIF\\($10^{-4}$)} & JIF \% & CIF \% & Gap \\ \midrule\endhead")
    out.append(r"\bottomrule\endfoot")

    for i, d in enumerate(rows, 1):
        venue = latex_escape(display_name(d["name"]))
        jif = f"{d['jif']:.1f}"
        cif = f"{d['cif']:.1f}"
        jp = f"{d['jif_pct']:.0f}"
        cp = f"{d['cif_pct']:.0f}"
        gap = f"{d['gap']:+.0f}"
        out.append(
            f"{i} & {venue} & {jif} & {cif} & {jp} & {cp} & {gap} \\\\"
        )

    out.append(r"\end{longtable}")
    with open(os.path.join(FIGS, "top_overperformers_rankgap.tex"), "w") as f:
        f.write("\n".join(out) + "\n")
    print(f"wrote figs/top_overperformers_rankgap.tex  ({TOP_N} rows)")


def main():
    import os
    os.chdir(os.path.dirname(os.path.abspath(__file__)))
    pool, n, coef = build_pool()
    print(f"pool: {n:,} venues (min {MIN_WORKS} works, JIF present, CIF > 0)")
    print(f"linear fit slope={coef[0]:.4f}, intercept={coef[1]:.3f}")
    emit_magnitude(pool, n)
    emit_rankgap(pool, n)


if __name__ == "__main__":
    main()
