"""Emit the two c_n tables of SM S6 (Tables S29 and S30).

  1. Top 15 venues by c_0, c_1, c_5 and c_inf, side by side.
  2. The top 20 venues by aggregate CIF with their c_n ranks, followed by the
     correlations of aggregate CIF with c_n and of normalized CIF with c_n / works.

Source: the venue table (ref_map/output/venue_basis.csv; c_n and CIF from Data S1).
Pool: journals and conferences with at least 1,000 works, excluding indexing
services (PubMed, ChemInform, Chemischer Informationsdienst, deleted sources).
"""
import csv
import os

from scipy.stats import pearsonr, spearmanr

import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from venue_data import DATA_PATH  # noqa: E402

OUTDIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "figs")
MIN_N = 1000
EXCLUDE = {"Deleted Journal", "ChemInform", "Chemischer Informationsdienst", "PubMed"}


def tex_num(n):
    """Thousands separator that survives LaTeX math mode: 28772 -> 28{,}772."""
    return f"{n:,}".replace(",", "{,}")


def latex_escape(s):
    if s is None:
        return ""
    for c, r in [("&", r"\&"), ("_", r"\_"), ("%", r"\%"), ("#", r"\#"), ("$", r"\$")]:
        s = s.replace(c, r)
    return s


DISPLAY_ALIASES = {
    'PLANT PHYSIOLOGY': 'Plant Physiology',
    'Proceedings of SPIE, the International Society for Optical Engineering/Proceedings of SPIE': 'Proceedings of SPIE',
    'Methods in enzymology on CD-ROM/Methods in enzymology': 'Methods in Enzymology',
    '2009 IEEE Conference on Computer Vision and Pattern Recognition': 'IEEE Computer Vision and Pattern Recognition',
    'Proceedings - International Conference on Image Processing': 'International Conference on Image Processing',
    # spelled out so the column does not mix acronyms with full journal names
    'BMJ': 'British Medical Journal',
    'JAMA': 'Journal of the American Medical Association',
}


UNICODE_FIX = {
    '′': "$'$",
    '’': "'",
    '″': "$''$",
    '‘': '`',
    '“': '``',
    '”': "''",
    '–': '--',
    '—': '---',
    '\xa0': ' ',
    '−': '$-$',
}


def _fix_unicode(s):
    for _k, _v in UNICODE_FIX.items():
        s = s.replace(_k, _v)
    return s


def display_name(name):
    if not name:
        return ""
    return _fix_unicode(DISPLAY_ALIASES.get(name.strip(), name))


def truncate(s, n):
    return s if len(s) <= n else s[: n - 1] + "\\ldots{}"




def load():
    rows = []
    with open(DATA_PATH) as f:
        for r in csv.DictReader(f):
            if r["source_name"].strip() in EXCLUDE:
                continue
            if r.get("source_type", "").strip() not in ("j", "c"):
                continue
            try:
                r["n"] = int(float(r.get("total_papers", "0") or 0))
                r["c0"] = float(r.get("all_reachable_papers_d0", "") or 0)
                r["c1"] = float(r.get("all_reachable_papers_d1", "") or 0)
                r["c5"] = float(r.get("all_reachable_papers_d5", "") or 0)
                r["cinf"] = float(r.get("reachable_papers", "") or 0)
                r["cif_agg"] = float(r.get("all_par_total_score", "") or 0)
            except ValueError:
                continue
            if r["n"] >= MIN_N:
                rows.append(r)
    return rows


def emit_top15_table(rows):
    """Top 15 side-by-side comparison of c_0, c_1, c_5, c_infty rankings."""
    keys = [("c0", "$c_0$"), ("c1", "$c_1$"), ("c5", "$c_5$"), ("cinf", "$c_\\infty$")]
    tops = {}
    for key, _ in keys:
        tops[key] = sorted(rows, key=lambda r: r[key], reverse=True)[:15]

    out = []
    out.append(r"% Autogenerated by emit_cn_tables.py")
    out.append(r"\begin{table}[h]")
    out.append(r"\centering")
    out.append(r"\footnotesize")
    out.append(
        r"\caption[Top 15 venues at each of $c_0$, $c_1$, $c_5$, and $c_\infty$]{\textbf{Top 15 venues at each of $c_0$, $c_1$, $c_5$, and $c_\infty$.} Over the "
        r"pool of journals and conferences with at least $1{,}000$ works. "
        r"Each count is cumulative in the citation distance. $c_0$ counts a venue's "
        r"articles that are themselves in the industry-absorbed seed set, $c_1$ those "
        r"within one citation hop upstream of a seed paper, $c_5$ those within five "
        r"hops, and $c_\infty$ those upstream of a seed paper at any distance. "
        r"$c_{10}$ tracks $c_\infty$ closely for essentially every venue and is omitted.}"
    )
    out.append(r"\label{tab:cn-topvenues}")
    out.append(r"\begin{tabular}{r p{0.21\textwidth} p{0.21\textwidth} p{0.21\textwidth} p{0.21\textwidth}}")
    out.append(r"\toprule")
    out.append(r"Rank & $c_0$ (in seed) & $c_1$ (within 1 hop) & $c_5$ (within 5 hops) & $c_\infty$ (any distance) \\")
    out.append(r"\midrule")
    for i in range(15):
        cells = [
            latex_escape(display_name(tops[k][i]["source_name"]))
            for k, _ in keys
        ]
        out.append(f"{i + 1} & " + " & ".join(cells) + r" \\")
    out.append(r"\bottomrule")
    out.append(r"\end{tabular}")
    out.append(r"\end{table}")

    with open(os.path.join(OUTDIR, "cn_topvenues.tex"), "w") as f:
        f.write("\n".join(out) + "\n")
    print(f"wrote {OUTDIR}/cn_topvenues.tex")


def emit_cif_vs_cn_table(rows):
    """CIF top 20 with c_0, c_1, c_5, c_infty ranks alongside."""
    ranks = {}
    for key in ("c0", "c1", "c5", "cinf", "cif_agg"):
        sorted_v = sorted(rows, key=lambda r: r[key], reverse=True)
        ranks[key] = {r["source_id"]: i + 1 for i, r in enumerate(sorted_v)}

    cif_top = sorted(rows, key=lambda r: r["cif_agg"], reverse=True)[:20]

    # Correlation of aggregate CIF with each c_n over the whole pool, reported
    # at the foot of the table: CIF is nearest c_0 in magnitude and nearest
    # c_1/c_5 in rank.
    cif = [r["cif_agg"] for r in rows]
    cif_n = [r["cif_agg"] / r["n"] for r in rows]
    corr = {k: (pearsonr([r[k] for r in rows], cif)[0],
                spearmanr([r[k] for r in rows], cif).correlation)
            for k in ("c0", "c1", "c5", "cinf")}
    # same comparison after dividing both sides by publication volume
    corr_n = {k: (pearsonr([r[k] / r["n"] for r in rows], cif_n)[0],
                  spearmanr([r[k] / r["n"] for r in rows], cif_n).correlation)
              for k in ("c0", "c1", "c5", "cinf")}
    vol_r = pearsonr([r["n"] for r in rows], cif)[0]
    vol_rho = spearmanr([r["n"] for r in rows], cif).correlation

    out = []
    out.append(r"% Autogenerated by emit_cn_tables.py")
    out.append(r"\begin{table}[h]")
    out.append(r"\centering")
    out.append(r"\small")
    out.append(
        r"\caption[Top 20 venues by aggregate CIF with their $c_n$ ranks]{\textbf{Top "
        r"20 venues by aggregate CIF with their $c_n$ ranks.} The $20$ highest-scoring "
        r"venues by aggregate CIF, with their ranks under $c_0$, $c_1$, $c_5$, and "
        r"$c_\infty$ alongside. "
        r"A venue ranked well above its $c_n$ rank, or well below it, marks where CIF's "
        r"weighting departs from a plain count at that radius. The last four rows give "
        r"correlations over "
        r"the whole reporting pool of Section~\ref{sm:cn-def}, the $"
        + tex_num(len(rows)) + r"$ journals and conferences with at least $"
        + tex_num(MIN_N) + r"$ works, excluding indexing services: aggregate CIF "
        r"against $c_n$, and normalized CIF against $c_n/N$, where $N$ is the venue's "
        r"number of works. Over the same pool, aggregate CIF correlates with "
        + rf"publication volume at $r = {vol_r:.3f}$ and $\rho = {vol_rho:.3f}$." + r"}"
    )
    out.append(r"\label{tab:cn-vs-cif}")
    out.append(r"\begin{tabular}{r p{0.42\textwidth} r r r r r}")
    out.append(r"\toprule")
    out.append(r"CIF rank & Venue & Agg.\ CIF & $c_0$ rk & $c_1$ rk & $c_5$ rk & $c_\infty$ rk \\")
    out.append(r"\midrule")
    for i, r in enumerate(cif_top, 1):
        name = latex_escape(display_name(r["source_name"]))
        cif = f"{r['cif_agg']:.0f}"
        r0 = ranks["c0"].get(r["source_id"], "--")
        r1 = ranks["c1"].get(r["source_id"], "--")
        r5 = ranks["c5"].get(r["source_id"], "--")
        rinf = ranks["cinf"].get(r["source_id"], "--")
        out.append(f"{i} & {name} & {cif} & {r0} & {r1} & {r5} & {rinf} \\\\")
    out.append(r"\midrule")
    for lbl, j, src in (
            (r"Pearson $r$: aggregate CIF vs.\ $c_n$", 0, corr),
            (r"Spearman $\rho$: aggregate CIF vs.\ $c_n$", 1, corr),
            (r"Pearson $r$: normalized CIF vs.\ $c_n/N$", 0, corr_n),
            (r"Spearman $\rho$: normalized CIF vs.\ $c_n/N$", 1, corr_n)):
        cells = " & ".join(f"{src[k][j]:.3f}" for k in ("c0", "c1", "c5", "cinf"))
        out.append(rf"\multicolumn{{3}}{{@{{}}l}}{{{lbl}}} & {cells} \\")
    out.append(r"\bottomrule")
    out.append(r"\end{tabular}")
    out.append(r"\end{table}")

    with open(os.path.join(OUTDIR, "cn_vs_cif.tex"), "w") as f:
        f.write("\n".join(out) + "\n")
    print(f"wrote {OUTDIR}/cn_vs_cif.tex")


def main():
    os.chdir(os.path.dirname(os.path.abspath(__file__)))
    os.makedirs(OUTDIR, exist_ok=True)
    rows = load()
    print(f"pool: {len(rows)} journals+conferences (>= {MIN_N} works, excluding aggregators)")
    emit_top15_table(rows)
    emit_cif_vs_cn_table(rows)


if __name__ == "__main__":
    main()
