"""Top venues under each assignee-class seed definition.

Emits figs/seed_scope_topvenues.tex: every venue that reaches the top 20 by
normalized CIF under at least one definition, with its rank under all four.
Aggregate top-20 overlaps are printed to stdout for the accompanying text,
which reports them without a table. Filters match the
other venue tables (emit_field_tables.py, emit_cn_tables.py): journals and
conferences only, indexing services excluded, at least 1,000 works.

Source: Data S1 (cif_seed_definitions; cif_all_documents for the all-assignee
definition and for works).
"""
import csv
import json
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, _HERE)
from venue_data import DATA_PATH, load_data_s1
from emit_cn_tables import tex_num
from emit_field_tables import DISPLAY_ALIASES, escape_unicode, latex_escape

OUT = os.path.join(_HERE, "figs", "seed_scope_topvenues.tex")

SCOPES = [("all_assignees", "All"), ("corporate", "Corp"),
          ("young_firm", "YF"), ("young_firm_university", "YF$+$U")]
EXCLUDE = {"Deleted Journal", "ChemInform", "Chemischer Informationsdienst",
           "PubMed"}
MIN_WORKS = 1000
TOP = 20


def score(rec, idx):
    """Aggregate score (idx 0) or per-work normalized score (idx 1)."""
    ts, tp = rec
    return ts if idx == 0 else (ts / tp if tp else 0.0)


_BASE = None
_DEFS = None


def load_scope(key):
    """(summed CIF, works) per journal/conference under one seed definition."""
    global _BASE, _DEFS
    if _BASE is None:
        _BASE = {r["source_id"]: r for r in load_data_s1("cif_all_documents")}
        _DEFS = {r["source_id"]: r for r in load_data_s1("cif_seed_definitions")}
    out = {}
    for sid, b in _BASE.items():
        if b.get("source_type") in ("j", "c"):
            ts = b.get("total_score") if key == "all_assignees" else _DEFS.get(sid, {}).get(key)
            out[sid] = (float(ts or 0.0), float(b.get("total_papers") or 0))
    return out


def main():
    name = {}
    with open(DATA_PATH) as f:
        for r in csv.DictReader(f):
            if r.get("source_id"):
                name[r["source_id"]] = (r.get("source_name") or "").strip()

    arms = {k: load_scope(k) for k, _ in SCOPES}
    keep = {s for s, (_, tp) in arms["all_assignees"].items()
            if tp >= MIN_WORKS and name.get(s, "") not in EXCLUDE}

    def ranks(idx):
        """Rank by score `idx` (0 aggregate, 1 normalized) under each scope."""
        rank, top = {}, {}
        for k, _ in SCOPES:
            order = sorted((s for s in arms[k] if s in keep),
                           key=lambda s: -score(arms[k][s], idx))
            rank[k] = {s: i + 1 for i, s in enumerate(order)}
            top[k] = order[:TOP]
        return rank, top

    def rows(union, rank):
        out = []
        for s in union:
            nm = DISPLAY_ALIASES.get(name.get(s, s), name.get(s, s))
            out.append(latex_escape(escape_unicode(nm)) + " & "
                       + " & ".join(str(rank[k][s]) for k, _ in SCOPES)
                       + r" \\")
        return out

    rank_a, top_a = ranks(0)
    rank_n, top_n = ranks(1)
    union_n = []
    for k, _ in SCOPES:
        for s in top_n[k]:
            if s not in union_n:
                union_n.append(s)
    union_n.sort(key=lambda s: rank_n["all_assignees"][s])

    head = ("Venue & " + " & ".join(lbl for _, lbl in SCOPES) + r" \\")
    out = [r"% Autogenerated by emit_seed_scope_topvenues.py",
           r"\footnotesize",
           r"\begin{longtable}{@{}p{0.52\textwidth}rrrr@{}}",
           r"\caption[Top venues by normalized CIF under each seed "
           r"definition]{\textbf{Top venues by normalized CIF under each "
           r"seed definition.} Rank by normalized CIF under the four "
           r"assignee-class seed definitions, for every venue that reaches "
           rf"the top ${TOP}$ under at least one of them, ordered by its "
           r"rank under the all-assignee definition. Journals and "
           r"conferences with at least $" + tex_num(MIN_WORKS)
           + r"$ works. PubMed, ChemInform, and Chemischer Informationsdienst "
           r"are excluded, since they index rather than publish. Definition "
           r"abbreviations follow Table~\ref{tab:universe-agreement}.}"
           r"\label{tab:seed-scope-topvenues}\\",
           r"\toprule", head, r"\midrule\endfirsthead",
           r"\multicolumn{5}{l}{\emph{Table~\ref{tab:seed-scope-topvenues} "
           r"(continued)}}\\",
           r"\toprule " + head + r" \midrule\endhead",
           r"\bottomrule\endfoot"]
    out += rows(union_n, rank_n)
    out += [r"\end{longtable}", r"\normalsize"]

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("\n".join(out) + "\n")
    print(f"wrote figs/seed_scope_topvenues.tex ({len(union_n)} rows)")
    inter = set(union_n)
    for k, _ in SCOPES:
        inter &= set(top_n[k])
    once = sum(1 for s in union_n
               if sum(s in top_n[k] for k, _ in SCOPES) == 1)
    print(f"  normalized: {len(inter)} venues in all four top-{TOP} lists, "
          f"{once} in exactly one")
    for idx, what, top in ((0, "aggregate", top_a), (1, "normalized", top_n)):
        shared = {lbl: len(set(top[k]) & set(top["all_assignees"]))
                  for k, lbl in SCOPES}
        print(f"  {what}: top-{TOP} shared with All: {shared}")


if __name__ == "__main__":
    main()
